name: Compile Minecraft Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Compiling Minecraft Mod
      uses: RuochenFu21/compilation@v1
